import assert from 'node:assert/strict'
import { CicloEscaner, cambioDeCarta } from '../src/features/scan/cicloEscaner.ts'

const ciclo = new CicloEscaner()
assert.equal(ciclo.admitirFotograma(1), true)
assert.equal(ciclo.admitirFotograma(1), false, 'vídeo congelado no aporta evidencia')
assert.equal(ciclo.admitirFotograma(1, true), true, 'el disparo explícito puede repetir')
assert.equal(ciclo.observar('A', 'arte', 1), false)
assert.equal(ciclo.observar('A', 'arte', 1), false, 'un mismo frame no confirma dos veces')
assert.equal(ciclo.observar('A', 'arte', 2), true)
const carta = Uint8Array.from([20, 180, 40, 200, 70, 170, 90, 190])
const exposicion = carta.map(x => x + 10)
const retirada = new Uint8Array(carta.length).fill(100)
assert.equal(cambioDeCarta(carta, exposicion), false)
assert.equal(cambioDeCarta(carta, retirada), true)
const anterior = ciclo.actual()
ciclo.bloquear('A', carta)
assert.equal(ciclo.vigente(anterior), false, 'hallazgo invalida OCR pendiente')
assert.equal(ciclo.observar('A', 'arte', 3), false)
assert.equal(ciclo.observar('A', 'texto', 4), false)
assert.equal(ciclo.observar('A', 'arte', 4, true), true)
assert.equal(ciclo.observarEscena(exposicion), false)
assert.equal(ciclo.observarEscena(retirada), false)
assert.equal(ciclo.observarEscena(carta), false, 'cambio fugaz no rearma')
assert.equal(ciclo.observarEscena(retirada), false)
assert.equal(ciclo.observarEscena(retirada), true)
assert.equal(ciclo.observar('A', 'arte', 5), false)
assert.equal(ciclo.observar('A', 'arte', 6), true)
ciclo.bloquear('A', carta)
assert.equal(ciclo.observar('B', 'arte', 7), false)
assert.equal(ciclo.observar('B', 'arte', 8), true, 'otra carta no exige retirar primero')
ciclo.bloquear('A', null)
assert.equal(ciclo.observarEscena(carta), false, 'la cámara adopta referencia después de una foto')
assert.equal(ciclo.observarEscena(retirada), false)
assert.equal(ciclo.observarEscena(retirada), true, 'foto y manual también permiten retirar y repetir')
const ocr = new CicloEscaner()
assert.equal(ocr.observar('A', 'texto', 1), false)
assert.equal(ocr.observar(null, 'arte', 2), false)
assert.equal(ocr.observar('A', 'texto', 3), true, 'fallos de arte no borran la evidencia OCR')

let terminar!: (valor: string) => void
const llamadas: string[] = []
const antiguo = ocr.actual()
const vivo = ocr.encolarTexto(antiguo, () => {
  llamadas.push('vídeo')
  return new Promise<string>(resolve => { terminar = resolve })
})
await Promise.resolve(); await Promise.resolve()
ocr.invalidar()
const foto = ocr.encolarTexto(ocr.actual(), async () => { llamadas.push('foto'); return 'B' })
await Promise.resolve()
assert.deepEqual(llamadas, ['vídeo'], 'foto espera el worker del vídeo anterior')
terminar('A')
assert.equal(await vivo, undefined, 'un resultado tardío no reabre confirmación')
assert.equal(await foto, 'B')
assert.deepEqual(llamadas, ['vídeo', 'foto'])
const invalido = ocr.actual()
ocr.invalidar()
await ocr.encolarTexto(invalido, async () => { throw new Error('No debería ejecutar una petición vieja') })
await assert.rejects(ocr.encolarTexto(ocr.actual(), async () => { throw new Error('Fallo del lector') }))
assert.equal(await ocr.encolarTexto(ocr.actual(), async () => 'reintento'), 'reintento', 'un fallo no atasca la cola OCR')
console.log('Escáner: fotogramas, estabilidad, retirada, exposición, generaciones y exclusión OCR verificados.')
